import createId from "@backend/utils/createId.ts";
import { toIsoStringWithTimezone } from "@backend/utils/date.ts";
import {
  JSONCompatible,
  JSONObject,
  Serializable,
} from "@backend/utils/objectTyping.ts";

/**
 * Number of tiles that the asset occupies physically on the map.
 */
type Dimensions = {
  width: number; // x-axis
  height: number; // y-axis
};

export type AssetId = string;

export type AssetsJSON = { [key: AssetId]: AssetJSON };
export type Assets = Map<AssetId, Asset>;

export interface AssetJSON extends JSONObject {
  _id: string;
  name: string;
  date: string;
  description: string;
  type: string;
  remoteImages: RemoteImageJSON[];
  dimensions: Dimensions;
}

export class Asset implements Serializable<AssetJSON> {
  public readonly _id: AssetId;
  public readonly name: string;
  public type: string;
  public description: string;
  public readonly date: Date;
  // Array of URLs to image in object storage, in order of processing
  // First image is the original image generated by OpenAI
  // Last image is the final image after all
  public readonly remoteImages: RemoteImage[];
  public dimensions: Dimensions;

  // For use on map visualiser frontend, cache loaded image element
  public imageEl: HTMLImageElement | null = null;

  constructor(
    description: string,
    name: string,
    type: string,
    date: Date = new Date(),
    id: AssetId = createId(),
    remoteImages: RemoteImage[] = [],
    dimensions: Dimensions = { width: 0, height: 0 }
  ) {
    this.description = description;
    this.type = type;
    this.date = date;
    this._id = id;
    this.remoteImages = remoteImages;
    this.dimensions = dimensions;
    this.name = name ?? this._id;
  }

  getFilename(): string {
    return `${this.name}.${this.type}`;
  }

  addRemoteImage(remoteObject: RemoteImage) {
    this.remoteImages.push(remoteObject);
  }

  getRemoteImages(): RemoteImage[] {
    return this.remoteImages;
  }

  serialize(): JSONCompatible<AssetJSON> {
    return {
      _id: this._id,
      name: this.name,
      type: this.type,
      date: toIsoStringWithTimezone(this.date),
      description: this.description,
      remoteImages: this.remoteImages.map((remoteImage) =>
        remoteImage.serialize()
      ),
      dimensions: this.dimensions,
    };
  }

  static deserialize(obj: AssetJSON): Asset {
    return new Asset(
      obj.description,
      obj.name,
      obj.type,
      new Date(obj.date),
      obj._id,
      obj.remoteImages.map((remoteImageObj) =>
        RemoteImage.deserialize(remoteImageObj)
      ),
      obj.dimensions
    );
  }
}

interface RemoteImageJSON extends JSONObject {
  name: string;
  url: string;
}
export class RemoteImage implements Serializable<RemoteImageJSON> {
  constructor(public name: string, public url: string) {}

  serialize(): JSONCompatible<RemoteImageJSON> {
    return {
      name: this.name,
      url: this.url,
    };
  }

  static deserialize(obj: JSONCompatible<RemoteImageJSON>): RemoteImage {
    return new RemoteImage(obj.name, obj.url);
  }
}
