# fly.toml app configuration file generated for trainee-earth-24t1-withered-sky-8391 on 2024-04-04T17:06:05+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trainee-earth-24t1-withered-sky-8391'
primary_region = 'syd'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
